### PR TITLE
Functional make

### PR DESCRIPTION
**Pull request by Peder2911**
This branch completes the basics of the dispatching / control structure for building priogrid. It is functional per this branch.

Of note is a change made to the use of intermediate data when making variables. Making some variables requires other datasets to be made, which complicates the build process. In this branch, i re-wrote the pgland-function so that it only generates a new set of data if the data doesn't exist already. If it does exist, the data is returned. This function is called by functions that require this data. This means that the call-order is completely arbitrary; the pgland data is made when calling the first function that requires it, and is then loaded from cache when it is needed.

This change is reflected in all of the different variable functions that depend on pgland. Take a look!

Completing the build-step for priogrid is now a matter of filling out the static "authorative_variable_names.csv" file, which is located in inst/extdata. This file, which is included with the package on install, directs the make-function, which means that all functions that are to be included in the make process must be in the file. Right now, it only has a couple of variables.

This pull request entails some pretty major changes, so please review the code before approving the merger.

P

### CODE REVIEW

**Comment by kvelleby** [comment]
I think this suggestion would involve having to nest all code in all gen_() functions with dependencies into a if..else structure. I think that creates quite a lot of complexity that we do not need. Two alternatives I rather would see are:

1. Caring about call-order in the build-step.
2. Creating get_[varname]() functions that essentially does what you suggest. I.e.:
`
get_pgland <- function(input_folder){
  pglandPath <- file.path(input_folder,"cache","pgland.rds")
     if(!file.exists(pglandPath)){
      pgland <- gen_pgland(input_folder)
  } else {
     pgland  <- read.parquet(pglandPath)
}
}
`

**Comment by Peder2911** [comment]
I do not agree with you in that this creates complexity, but the current solution is more verbose. 

A solution would be to write a decorator function that would wrap all of these functions, which could be applied to all of them at build-time; this would avoid putting any of this code in the gen-functions themselves, which would be generalized in the wrapper.

Gen vs. get functions would then just be a difference between the wrapped function and its "vanilla" counterpart. In the flow of the gen program, there wouldn't be a difference. Remember; the only semantic difference between getting and generating the data for each variable is in how it is done (which should be irrelevant), not in what you get (which is the same).

**Comment by Peder2911** [comment]
So your proposal is to amend this branch before merging?

**Comment by Peder2911** [comment]
Keeping track of execution order is not a very good idea imo. It would make it even more tedious to keep track of all of the variables, which is currently also a chore. A problem better solved by computation than with human-time!

**Comment by kvelleby** [comment]
Haha, yes. I think if it is amended with a proposal to write the get-functions (or equivalent) and then use those whenever dependencies are needed, I am happy. I agree that what I get is the same, it is only a "flatter" structure in terms of the code.

On the rds versus parquet, I do not agree. We use parquet extensively, and it is a core dependency. It saves minutes for some variables, and the arrow installation is now straight-forward. Of course, for small tables like pgland, rds is just as good, but most output data is .parquet and very large tables.

**Comment by Peder2911** [comment]
Great! The way i wrote it above the caching won't be in the gen functions at all, it will be implemented by wrapping each of the functions at build-time. It is a much cleaner solution, thanks for helping me figure this out!

I actually forgot that i also made the proposal for RDS. I think it was just a matter of trying to reduce the dependency-creep, but if you want to keep it as a core dep. then it's not really an issue.

**Comment by Peder2911** [comment]
Amending, will create a pull request at a later point.

**Pull request closed without merging**
